type: rpm-ostree
install:
# launcher
  - rofi-wayland

# environment
  - xorg-x11-server-Xwayland
  - polkit
  - lxpolkit
  - xdg-user-dirs
  - dbus-tools
  - dbus-daemon
  - wl-clipboard
  - gnome-keyring
  - pavucontrol
  - playerctl
  - qt5-qtwayland
  - qt6-qtwayland
  - vulkan-validation-layers
  - vulkan-tools
  - google-noto-emoji-fonts
  - gnome-disk-utility
  - bash-completion
  - bzip2
  - gcc
  - gcc-c++
  - git
  - make
  - ncurses-devel
  - patch
  - rsync 
  - tar 
  - unzip
  - wget
  - which
  - diffutils
  - python3
  - perl-base
  - perl-Data-Dumper
  - perl-File-Compare
  - perl-File-Copy
  - perl-FindBin
  - perl-IPC-Cmd
  - perl-JSON-PP
  - perl-Thread-Queue
  - perl-Time-Piece
  - re2c
  - libreoffice
  - virt-viewer
  - virt-manager
  - virt-install
  - nodejs
  - npm
  - rpi-imager
  
# sound
  - wireplumber
  - pipewire
  - pamixer

# networking
  - network-manager-applet
  - NetworkManager-openvpn
  - NetworkManager-openconnect
  - bluez
  - bluez-tools
  - blueman

# file manager
  - thunar
  - thunar-archive-plugin 
  - thunar-volman
  - xarchiver
  - imv
  - p7zip
  - unrar-free

# screenshot
  - slurp
  - grim

# display
  - wlr-randr
  - wlsunset
  - brightnessctl
  - swaylock
  - swayidle
  - kanshi

# terminal
  - foot
  - tilix
  - zsh
  - kubernetes-client
  - go
  - rust
  - mc
  - telegram-desktop
  - xrandr
  - nmap


# notifications
  - dunst

# theme and GUI
  - adwaita-qt5
  - fontawesome-fonts-all
  - gnome-themes-extra
  - gnome-icon-theme
  - paper-icon-theme
  - breeze-icon-theme 
  - papirus-icon-theme
