# image will be published to ghcr.io/<user>/<name>
name: quantum-hyprland-nvidia
# description will be included in the image's metadata
description: ublue images for wayland compositors

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      # - 1password # install 1Password (stable) and `op` CLI tool
      - ublue-update # https://github.com/ublue-os/ublue-update
      - dconf-update-service # a service unit that updates the dconf db on boot
      - laptop # installs TLP and configures your system for laptop usage  
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
        - Hack
        - SourceCodePro
        - Terminus
        - JetBrainsMono
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
  - type: rpm-ostree
    repos:
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/alebastr/sway-extras/repo/fedora-40/alebastr-sway-extras-fedora-40.repo
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - tailscale
      - swww
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      # - firefox
      # - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
 
  - from-file: sddm-packages.yml
  - from-file: common-packages.yml
  - from-file: hyprland-packages.yml
 
  - type: files
    files:
      - usr: /usr

  - from-file: common-files.yml
  - from-file: common-scripts.yml
  - from-file: hyprland-scripts.yml  
  - from-file: sddm-scripts.yml
  - type: signing
  - from-file: sddm-systemd.yml
