# Shell variables
# Generated by 'wal'
wallpaper='/home/dingo/Pictures/wallpapers/Dynamic-Wallpapers/Light/City_light.jpg'

# Special
background='#0c0e12'
foreground='#c6c7c9'
cursor='#c6c7c9'

# Colors
color0='#0c0e12'
color1='#3D6391'
color2='#4D739B'
color3='#6C788A'
color4='#527AA1'
color5='#138F94'
color6='#6D8A9F'
color7='#c6c7c9'
color8='#8a8b8c'
color9='#3D6391'
color10='#4D739B'
color11='#6C788A'
color12='#527AA1'
color13='#138F94'
color14='#6D8A9F'
color15='#c6c7c9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
