--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/dingo/Pictures/wallpapers/Dynamic-Wallpapers/Light/City_light.jpg"

-- Special
background="#0c0e12"
foreground="#c6c7c9"
cursor="#c6c7c9"

-- Colors
color0="#0c0e12"
color1="#3D6391"
color2="#4D739B"
color3="#6C788A"
color4="#527AA1"
color5="#138F94"
color6="#6D8A9F"
color7="#c6c7c9"
color8="#8a8b8c"
color9="#3D6391"
color10="#4D739B"
color11="#6C788A"
color12="#527AA1"
color13="#138F94"
color14="#6D8A9F"
color15="#c6c7c9"
